"""
Seed content for the AI Interview Prep platform.
Categories + curated question bank used by main.py on first boot.
"""

CATEGORIES = [
    {
        "slug": "machine-learning",
        "name": "Machine Learning",
        "code": "ML",
        "description": "Core algorithms, training theory, and the tradeoffs that show up in every ML interview.",
    },
    {
        "slug": "deep-learning",
        "name": "Deep Learning",
        "code": "DL",
        "description": "Neural network architectures, optimization, and the mechanics of training them.",
    },
    {
        "slug": "nlp",
        "name": "NLP",
        "code": "NLP",
        "description": "Text representation, sequence models, and the foundations behind modern language tech.",
    },
    {
        "slug": "computer-vision",
        "name": "Computer Vision",
        "code": "CV",
        "description": "Convolutional networks, detection, and how machines learn to see.",
    },
    {
        "slug": "statistics",
        "name": "Statistics & Probability",
        "code": "STAT",
        "description": "The math underneath every model — distributions, inference, and experiment design.",
    },
    {
        "slug": "mlops",
        "name": "MLOps",
        "code": "OPS",
        "description": "Shipping, monitoring, and maintaining models once they leave the notebook.",
    },
    {
        "slug": "generative-ai",
        "name": "Generative AI & LLMs",
        "code": "GEN",
        "description": "Transformers, large language models, and the generative systems built on top of them.",
    },
    {
        "slug": "sql",
        "name": "SQL",
        "code": "SQL",
        "description": "Joins, aggregation, and the query patterns every data role leans on daily.",
    },
    {
        "slug": "numpy",
        "name": "NumPy",
        "code": "NP",
        "description": "Vectorization, broadcasting, and the array mechanics underneath most of the ML stack.",
    },
    {
        "slug": "pandas",
        "name": "Pandas",
        "code": "PD",
        "description": "Wrangling, reshaping, and cleaning tabular data — the unglamorous majority of real ML work.",
    },
    {
        "slug": "system-design",
        "name": "System Design",
        "code": "SYS",
        "description": "Scaling, serving, and architecting systems — including ML systems — under real-world constraints.",
    },
]

# Each question: category slug, question, answer (concise), deep_dive (extended),
# difficulty (Beginner/Intermediate/Advanced), frequency (1-5, editorial "how often asked"), tags
QUESTIONS = [
    # ---------------- MACHINE LEARNING ----------------
    dict(category="machine-learning", difficulty="Beginner", frequency=5,
         tags=["overfitting", "generalization"],
         question="What is overfitting, and how do you detect it?",
         answer="Overfitting happens when a model learns the noise and quirks of the training data rather than the underlying pattern, so it performs well on training data but poorly on unseen data.",
         deep_dive="You detect it by watching the gap between training and validation loss — a model that keeps improving on training data while validation performance stalls or worsens is overfitting. Common fixes include regularization, more data, simpler models, dropout, and early stopping based on validation performance."),
    dict(category="machine-learning", difficulty="Beginner", frequency=5,
         tags=["bias-variance", "model-complexity"],
         question="Explain the bias-variance tradeoff.",
         answer="Bias is error from overly simplistic assumptions (underfitting); variance is error from sensitivity to small fluctuations in training data (overfitting).",
         deep_dive="Expected error decomposes into bias squared, variance, and irreducible noise. Reducing one often increases the other, so the goal is finding the model complexity that minimizes both together — regularization, ensembling, and learning curves are the practical tools for navigating this tradeoff."),
    dict(category="machine-learning", difficulty="Intermediate", frequency=5,
         tags=["ensemble", "boosting", "random-forest"],
         question="What's the difference between bagging and boosting?",
         answer="Bagging trains many independent models in parallel on random subsets of data and averages their predictions to reduce variance; boosting trains models sequentially, each correcting the prior model's errors.",
         deep_dive="Random Forest is the classic bagging example. Boosting (AdaBoost, Gradient Boosting, XGBoost) reduces bias but can overfit if unchecked since later trees focus heavily on hard or residual examples — learning rate and tree depth are the usual regularizers."),
    dict(category="machine-learning", difficulty="Beginner", frequency=4,
         tags=["decision-trees", "entropy", "gini"],
         question="How does a decision tree decide where to split?",
         answer="At each node, the tree evaluates possible feature thresholds and picks the split that most reduces impurity in the child nodes, using Gini impurity or information gain for classification.",
         deep_dive="It repeats this greedily at every node until a stopping condition (max depth, min samples per leaf) is reached. Because splits are chosen greedily, the result isn't guaranteed globally optimal — pruning and ensembling help compensate."),
    dict(category="machine-learning", difficulty="Beginner", frequency=5,
         tags=["regularization", "l1", "l2"],
         question="What is regularization, and why does it help?",
         answer="Regularization adds a penalty term to the loss function that discourages overly complex models, typically by shrinking weight magnitudes.",
         deep_dive="L1 (Lasso) penalizes the sum of absolute weights and tends to zero out less useful features, producing sparse solutions. L2 (Ridge) penalizes the sum of squared weights and shrinks them smoothly without eliminating them. Elastic Net combines both."),
    dict(category="machine-learning", difficulty="Intermediate", frequency=5,
         tags=["class-imbalance", "smote", "evaluation"],
         question="How do you handle class imbalance in a classification problem?",
         answer="Common approaches: resampling (oversampling the minority class with SMOTE, or undersampling the majority), adjusting class weights in the loss, and using metrics like precision, recall, and F1 instead of accuracy.",
         deep_dive="Accuracy is misleading when classes are imbalanced — a model predicting the majority class every time can still score high. Threshold tuning and stratified train/test splits also matter; for extreme imbalance, framing the problem as anomaly detection can work better."),
    dict(category="machine-learning", difficulty="Beginner", frequency=5,
         tags=["precision", "recall", "f1-score"],
         question="What's the difference between precision and recall, and when would you prioritize one?",
         answer="Precision measures how many predicted positives are actually positive; recall measures how many actual positives the model found.",
         deep_dive="Prioritize precision when false positives are costly (spam filters wrongly blocking real email); prioritize recall when false negatives are costly (missing a diagnosis). F1 is the harmonic mean when you need a single balanced metric."),
    dict(category="machine-learning", difficulty="Beginner", frequency=4,
         tags=["cross-validation", "k-fold"],
         question="Explain cross-validation and why it's used.",
         answer="Cross-validation splits data into folds and trains and evaluates the model multiple times, holding out a different fold each round, then averages results for a more reliable generalization estimate.",
         deep_dive="K-fold is standard; stratified k-fold preserves class ratios for imbalanced data. For time-series, you need chronological splits instead of random shuffling, since future data leaking into training would be unrealistic."),
    dict(category="machine-learning", difficulty="Intermediate", frequency=3,
         tags=["curse-of-dimensionality", "knn"],
         question="What is the curse of dimensionality?",
         answer="As feature count grows, the feature space volume grows exponentially, so data becomes sparse and distance-based notions like 'nearest neighbor' become less meaningful.",
         deep_dive="It especially hurts distance-based models such as KNN and clustering, and means you typically need exponentially more data to keep the same data density. Dimensionality reduction (PCA, t-SNE, UMAP) is the common mitigation."),
    dict(category="machine-learning", difficulty="Beginner", frequency=4,
         tags=["clustering", "k-means"],
         question="How does k-means clustering work, and what are its limitations?",
         answer="K-means randomly initializes k centroids, assigns points to the nearest centroid, recomputes centroids as the mean of assigned points, and repeats until convergence.",
         deep_dive="Limitations: you must choose k in advance, it assumes roughly spherical, similar-sized clusters, and it's sensitive to initialization and outliers. K-means++ improves initialization; the elbow method or silhouette score help choose k."),
    dict(category="machine-learning", difficulty="Intermediate", frequency=4,
         tags=["feature-engineering", "tabular-data"],
         question="What is feature engineering, and why does it still matter in the era of deep learning?",
         answer="Feature engineering transforms raw data into representations that make patterns easier for a model to learn — ratios, binning, encodings, domain-specific signals.",
         deep_dive="It still matters because most real-world business problems involve structured or tabular data, where gradient-boosted trees with good features often beat raw deep nets. Deep learning shines instead on unstructured data like images and text, where it learns features automatically."),
    dict(category="machine-learning", difficulty="Intermediate", frequency=3,
         tags=["parametric-models", "model-types"],
         question="What's the difference between parametric and non-parametric models?",
         answer="Parametric models assume a fixed functional form with a fixed parameter count, like linear or logistic regression; non-parametric models can grow in complexity as more data is added, like KNN or decision trees.",
         deep_dive="Non-parametric doesn't mean 'no parameters' — just that the count isn't fixed in advance. Non-parametric models are more flexible but typically need more data and are more prone to overfitting."),

    # ---------------- DEEP LEARNING ----------------
    dict(category="deep-learning", difficulty="Beginner", frequency=5,
         tags=["backpropagation", "gradient-descent"],
         question="What is backpropagation?",
         answer="Backpropagation computes the gradient of the loss with respect to every weight by applying the chain rule backward from the output, layer by layer.",
         deep_dive="These gradients are then used by an optimizer like gradient descent to update weights. It's efficient because it reuses intermediate computations from the forward pass rather than recomputing derivatives from scratch for every parameter."),
    dict(category="deep-learning", difficulty="Beginner", frequency=5,
         tags=["activation-functions", "relu", "sigmoid"],
         question="Why do we need activation functions, and how do ReLU and sigmoid differ?",
         answer="Activation functions introduce non-linearity — without them, stacking any number of linear layers collapses into one linear function.",
         deep_dive="Sigmoid squashes outputs into the range zero to one but saturates for large inputs, causing vanishing gradients. ReLU outputs the input directly if positive, zero otherwise — faster training, no saturation on the positive side, though 'dead neurons' can occur. GELU is common in transformers."),
    dict(category="deep-learning", difficulty="Intermediate", frequency=4,
         tags=["vanishing-gradient", "resnet"],
         question="What causes vanishing and exploding gradients, and how do you address them?",
         answer="Gradients are products of many partial derivatives during backprop; if consistently less than one they shrink toward zero (vanishing), if consistently greater than one they grow unboundedly (exploding).",
         deep_dive="Fixes: non-saturating activations like ReLU, careful initialization (Xavier or He), batch normalization, gradient clipping for exploding gradients, and skip connections (ResNets) or gating (LSTMs) that give gradients a more direct path backward."),
    dict(category="deep-learning", difficulty="Intermediate", frequency=4,
         tags=["batch-normalization", "training-stability"],
         question="What is batch normalization, and why does it help training?",
         answer="Batch norm normalizes a layer's inputs to zero mean and unit variance across each mini-batch, then applies a learnable scale and shift.",
         deep_dive="It stabilizes and speeds up training, allows higher learning rates, and acts as a mild regularizer. LayerNorm is often preferred for sequence models and transformers since it doesn't depend on batch size."),
    dict(category="deep-learning", difficulty="Beginner", frequency=4,
         tags=["dropout", "regularization"],
         question="Explain dropout and why it prevents overfitting.",
         answer="Dropout randomly zeroes a fraction of neurons during each training step, forcing the network not to rely too heavily on any single neuron.",
         deep_dive="This effectively trains an ensemble of thinned sub-networks sharing weights. At test time all neurons are active, with outputs scaled to match the expected magnitude seen during training. It's used less in some modern transformer architectures that rely on other regularization and scale."),
    dict(category="deep-learning", difficulty="Beginner", frequency=4,
         tags=["cnn", "convolution"],
         question="What's the difference between a CNN and a fully connected network for image data?",
         answer="A fully connected layer treats every pixel independently, ignoring spatial structure and needing huge parameter counts; a CNN uses small shared filters that slide across the image.",
         deep_dive="Weight sharing drastically cuts parameters and builds in translation invariance — a useful local pattern is detected anywhere in the image. Pooling adds spatial downsampling, and stacking layers builds a hierarchy: edges, then textures, then object parts."),
    dict(category="deep-learning", difficulty="Intermediate", frequency=4,
         tags=["optimizers", "adam", "sgd"],
         question="What is the difference between Adam and plain SGD as optimizers?",
         answer="Plain SGD applies a fixed or scheduled learning rate uniformly to the raw gradient; Adam adapts the learning rate per parameter using running estimates of the gradient's mean and variance.",
         deep_dive="Adam usually converges faster, but SGD with momentum can sometimes generalize better. AdamW decouples weight decay from the gradient update, which is now standard for training transformers."),
    dict(category="deep-learning", difficulty="Beginner", frequency=5,
         tags=["transfer-learning", "fine-tuning"],
         question="What is transfer learning, and when is it useful?",
         answer="Transfer learning takes a model pretrained on a large dataset and fine-tunes it on a smaller, task-specific dataset, reusing previously learned general features.",
         deep_dive="It's especially useful with limited labeled data. You can freeze the backbone and train only a new head (feature extraction) or fine-tune the whole network. This idea underlies most modern CV and NLP pipelines, including LLM fine-tuning."),
    dict(category="deep-learning", difficulty="Beginner", frequency=4,
         tags=["learning-rate", "optimization"],
         question="What is the role of learning rate, and what happens if it's too high or too low?",
         answer="The learning rate controls how big a step the optimizer takes toward the negative gradient at each update.",
         deep_dive="Too high: training overshoots and can diverge or oscillate. Too low: training converges slowly and can get stuck on plateaus. Schedules like warmup and cosine decay, plus learning-rate finders, are common practical tools."),
    dict(category="deep-learning", difficulty="Intermediate", frequency=4,
         tags=["resnet", "residual-connections"],
         question="What is a residual (skip) connection, and why did ResNet introduce it?",
         answer="A residual connection adds a layer's input directly to its output, so the network only needs to learn the change rather than the entire mapping.",
         deep_dive="This let networks go far deeper by giving gradients a direct path backward, avoiding the degradation problem where stacking more plain layers made performance worse. The same residual-plus-normalization pattern underlies modern transformer blocks."),
    dict(category="deep-learning", difficulty="Intermediate", frequency=3,
         tags=["autoencoder", "gan", "generative-models"],
         question="What's the difference between an autoencoder and a GAN?",
         answer="An autoencoder compresses input into a latent representation and reconstructs it, minimizing reconstruction error directly; a GAN pits a generator against a discriminator in an adversarial game.",
         deep_dive="GANs tend to produce sharper, more realistic samples than typical autoencoders. VAEs sit as a probabilistic middle ground. Diffusion models have largely overtaken GANs for state-of-the-art image generation."),
    dict(category="deep-learning", difficulty="Beginner", frequency=3,
         tags=["weight-initialization", "symmetry-breaking"],
         question="Why do we initialize neural network weights randomly instead of to zero?",
         answer="If all weights start identical, every neuron in a layer computes the same gradient and updates identically — they never differentiate. This is called the symmetry problem.",
         deep_dive="Random initialization breaks this symmetry. Xavier or Glorot and He initialization scale the random values based on layer size to keep activation variance stable across depth, which matters a lot in very deep networks."),

    # ---------------- NLP ----------------
    dict(category="nlp", difficulty="Beginner", frequency=5,
         tags=["tokenization", "bpe"],
         question="What is tokenization, and why do modern models use subword tokenization?",
         answer="Tokenization splits raw text into units a model can process. Subword tokenization, like BPE or WordPiece, keeps common words as single tokens but breaks rare words into known smaller pieces.",
         deep_dive="This keeps vocabulary size manageable while avoiding the out-of-vocabulary problem of word-level tokenization. BPE starts from characters and iteratively merges the most frequent pairs, so the same tokenizer can handle any text, including typos or new words."),
    dict(category="nlp", difficulty="Beginner", frequency=3,
         tags=["tfidf", "bag-of-words"],
         question="What is TF-IDF, and what problem does it solve compared to raw word counts?",
         answer="TF-IDF weighs a word by how often it appears in a document but discounts it if it's common across the whole corpus, down-weighting uninformative words like 'the'.",
         deep_dive="Raw counts alone let frequent-but-uninformative words dominate. TF-IDF is still useful as a fast baseline for search and simple classification, though dense embeddings now generally outperform it for semantic tasks."),
    dict(category="nlp", difficulty="Intermediate", frequency=5,
         tags=["word-embeddings", "bert"],
         question="What are word embeddings, and how do Word2Vec and contextual embeddings like BERT differ?",
         answer="Word embeddings represent words as dense vectors where semantically similar words are close together. Word2Vec gives one fixed vector per word; contextual embeddings give a different vector depending on the sentence.",
         deep_dive="'Bank' has the same Word2Vec vector in 'river bank' and 'bank account,' but a contextual model like BERT produces different vectors for each, since the full sentence is run through the network to compute the embedding."),
    dict(category="nlp", difficulty="Intermediate", frequency=5,
         tags=["attention", "rnn", "lstm"],
         question="What problem does attention solve that plain RNNs and LSTMs struggled with?",
         answer="RNNs and LSTMs compress everything seen so far into a single fixed-size hidden state, a bottleneck for long sequences. Attention lets the model directly look back at all previous tokens and weigh their relevance.",
         deep_dive="This removes the long-range dependency bottleneck and, just as importantly, enables parallel training since tokens don't have to be processed strictly in sequence — the core motivation behind 'Attention is All You Need.'"),
    dict(category="nlp", difficulty="Advanced", frequency=5,
         tags=["self-attention", "transformer"],
         question="How does the self-attention mechanism in transformers actually work?",
         answer="Each token is projected into query, key, and value vectors. Attention scores come from the dot product of one token's query with another's key, then softmax-weighted to combine value vectors.",
         deep_dive="Multi-head attention runs this in parallel with different learned projections to capture different relationships. The scaling factor of one over the square root of the key dimension prevents large dot products from pushing softmax into regions with vanishing gradients."),
    dict(category="nlp", difficulty="Intermediate", frequency=3,
         tags=["ner", "sequence-labeling"],
         question="What is Named Entity Recognition, and how is it typically framed as an ML problem?",
         answer="NER identifies and classifies text spans into categories like person, organization, or location. It's framed as sequence labeling, tagging each token, often with BIO notation.",
         deep_dive="Historically modeled with BiLSTM-CRF; today it's usually a fine-tuned transformer encoder with a token classification head. The CRF layer's job, when used, is enforcing valid tag transitions."),
    dict(category="nlp", difficulty="Intermediate", frequency=3,
         tags=["perplexity", "language-modeling"],
         question="What is perplexity, and what does it measure in a language model?",
         answer="Perplexity is the exponentiated average negative log-likelihood a model assigns to held-out text — lower means the model is less surprised by the actual words, i.e. a better fit.",
         deep_dive="A perplexity of N means the model is, on average, as uncertain as choosing uniformly among N equally likely next tokens. It's tokenizer-dependent, so you can't directly compare across models with different vocabularies, and it doesn't always track downstream quality."),
    dict(category="nlp", difficulty="Beginner", frequency=3,
         tags=["stemming", "lemmatization"],
         question="What's the difference between stemming and lemmatization?",
         answer="Stemming crudely chops word endings with fixed rules, often producing non-words, like 'studies' becoming 'studi.' Lemmatization uses grammar and vocabulary to return the proper dictionary form, like 'studies' becoming 'study.'",
         deep_dive="With modern subword tokenizers and contextual embeddings, this preprocessing step matters far less than it did for classic bag-of-words pipelines."),
    dict(category="nlp", difficulty="Intermediate", frequency=4,
         tags=["encoder-decoder", "seq2seq"],
         question="What is the encoder-decoder architecture, and what kinds of tasks is it used for?",
         answer="An encoder processes the input into a contextual representation; a decoder generates output step by step, attending back to that representation and its own prior outputs.",
         deep_dive="Natural fit for sequence-to-sequence tasks like translation, summarization, or speech-to-text. Compare to encoder-only models like BERT, good for understanding and classification, and decoder-only models like GPT, good for open-ended generation, which dominate today's LLMs."),
    dict(category="nlp", difficulty="Intermediate", frequency=2,
         tags=["bleu", "evaluation-metrics"],
         question="What is BLEU score, and what are its limitations?",
         answer="BLEU measures n-gram overlap between generated text and human reference text, with a brevity penalty to discourage short outputs.",
         deep_dive="It only checks surface-level word overlap, so it can penalize valid paraphrases using different wording. Newer metrics like BERTScore or COMET compare meaning via embeddings; human evaluation remains the gold standard."),

    # ---------------- COMPUTER VISION ----------------
    dict(category="computer-vision", difficulty="Beginner", frequency=4,
         tags=["convolution", "feature-maps"],
         question="What does a convolutional filter actually learn?",
         answer="A convolutional filter is a small grid of learnable weights that slides across the image, producing a feature map highlighting where a pattern occurs.",
         deep_dive="Early layers learn simple, generic features like edges and color gradients; deeper layers combine these into complex, task-specific patterns like textures, shapes, and object parts. This hierarchy is why early layers of pretrained CNNs transfer well across very different tasks."),
    dict(category="computer-vision", difficulty="Beginner", frequency=3,
         tags=["pooling", "cnn"],
         question="What is the role of pooling layers in a CNN?",
         answer="Pooling layers downsample feature maps by summarizing small spatial regions into one value, reducing computation and adding mild translation invariance.",
         deep_dive="Many modern architectures replace pooling with strided convolutions instead, since pooling discards spatial information that matters for tasks like segmentation."),
    dict(category="computer-vision", difficulty="Intermediate", frequency=4,
         tags=["object-detection", "segmentation"],
         question="What's the difference between object detection and image segmentation?",
         answer="Object detection localizes objects with bounding boxes plus a class label; segmentation classifies every pixel — semantic segmentation by class, instance segmentation separates individual objects too.",
         deep_dive="Representative architectures: detection uses YOLO or Faster R-CNN; segmentation uses U-Net or Mask R-CNN."),
    dict(category="computer-vision", difficulty="Beginner", frequency=4,
         tags=["data-augmentation", "regularization"],
         question="What is data augmentation, and why is it especially important in computer vision?",
         answer="Data augmentation expands a training set with label-preserving transformations — flips, rotations, crops, color jitter.",
         deep_dive="Labeled image data is expensive, and augmentation helps the model become invariant to changes that shouldn't affect the prediction. Advanced techniques like MixUp and CutMix blend examples together as another form of regularization."),
    dict(category="computer-vision", difficulty="Intermediate", frequency=4,
         tags=["iou", "object-detection"],
         question="What is IoU, and how is it used in object detection?",
         answer="IoU, or Intersection over Union, measures overlap between a predicted box and ground truth — intersection area divided by union area, from zero (no overlap) to one (perfect overlap).",
         deep_dive="Used to define a 'correct' detection, for example IoU above 0.5, for metrics like mAP, and within Non-Maximum Suppression: keep the highest-confidence box, suppress others overlapping it above an IoU threshold."),
    dict(category="computer-vision", difficulty="Advanced", frequency=3,
         tags=["vision-transformer", "vit"],
         question="How does a Vision Transformer process an image differently from a CNN?",
         answer="A Vision Transformer splits the image into fixed-size patches, projects each into a token embedding plus a position embedding, and feeds the sequence through a standard transformer encoder.",
         deep_dive="Unlike CNNs, it has no built-in locality or translation invariance — it must learn spatial relationships from data, which is why ViTs typically need larger training sets, but scale very well once they have it, and now underpin many state-of-the-art vision and multimodal systems."),
    dict(category="computer-vision", difficulty="Beginner", frequency=4,
         tags=["transfer-learning", "imagenet"],
         question="What is transfer learning's role specifically in computer vision, and why does ImageNet pretraining matter?",
         answer="A CNN pretrained on ImageNet learns a hierarchy of general-purpose visual features useful far beyond its original one thousand classes.",
         deep_dive="Fine-tuning this backbone on a smaller, domain-specific dataset typically converges faster and generalizes better than random initialization. Freezing early, generic layers and only fine-tuning later, task-specific layers is common when data is very scarce."),
    dict(category="computer-vision", difficulty="Intermediate", frequency=3,
         tags=["resnet", "deep-cnn"],
         question="What was the vanishing gradient problem's specific impact on very deep CNNs, and how did architectures evolve to address it?",
         answer="Before residual connections, stacking more convolutional layers eventually hurt training — gradients shrank propagating back, and accuracy could degrade with depth, known as the degradation problem.",
         deep_dive="ResNet's skip connections gave gradients a direct shortcut path, finally making 50, 100, even 1000-plus layer networks trainable. DenseNet extends the same idea with even denser connectivity."),

    # ---------------- STATISTICS & PROBABILITY ----------------
    dict(category="statistics", difficulty="Beginner", frequency=4,
         tags=["central-limit-theorem", "sampling"],
         question="What is the Central Limit Theorem, and why does it matter for ML?",
         answer="The CLT states that the sampling distribution of the mean of enough independent, identically distributed random variables approaches a normal distribution, regardless of the original distribution's shape.",
         deep_dive="It justifies why averaging — over batches, bootstraps, ensembles — produces more stable, normally-distributed estimates, and underlies many statistical tests and confidence intervals used in model evaluation."),
    dict(category="statistics", difficulty="Intermediate", frequency=4,
         tags=["p-value", "confidence-interval"],
         question="What's the difference between a p-value and a confidence interval?",
         answer="A p-value is the probability of seeing a result at least as extreme as observed, assuming the null hypothesis is true. A confidence interval gives a range of plausible values for the true parameter.",
         deep_dive="Common misconception: a 95 percent confidence interval does not mean there's a 95 percent probability the true value is in this specific interval — it describes how often intervals built this way would contain the true value across repeated sampling."),
    dict(category="statistics", difficulty="Beginner", frequency=4,
         tags=["type-i-error", "type-ii-error"],
         question="What is the difference between Type I and Type II error?",
         answer="Type I is a false positive — rejecting a true null hypothesis. Type II is a false negative — failing to reject a false null hypothesis.",
         deep_dive="There's a tradeoff between them controlled by your significance threshold and statistical power. These map conceptually to false positives and negatives in a confusion matrix, and to the precision and recall tradeoff."),
    dict(category="statistics", difficulty="Beginner", frequency=5,
         tags=["bayes-theorem", "naive-bayes"],
         question="Explain Bayes' Theorem and give an intuition for why it's useful.",
         answer="Bayes' Theorem updates a belief about a hypothesis given new evidence, combining a prior belief with how likely the evidence is under that hypothesis.",
         deep_dive="It formalizes learning from data — starting with an assumption and rationally revising it as evidence arrives. Naive Bayes classifiers apply this directly, assuming feature independence given the class to keep computation tractable."),
    dict(category="statistics", difficulty="Beginner", frequency=4,
         tags=["correlation", "causation"],
         question="What is the difference between correlation and causation, and why does it matter for model interpretation?",
         answer="Correlation means two variables move together statistically — that alone doesn't establish that one causes the other, or rule out a confounding variable driving both.",
         deep_dive="A model can find genuinely predictive correlations without understanding causal mechanisms, which means merely-correlated features can break badly if the underlying relationship shifts. Causal inference techniques, like A/B tests or instrumental variables, are how you actually establish causation."),
    dict(category="statistics", difficulty="Intermediate", frequency=3,
         tags=["confounding-variable", "ab-testing"],
         question="What is a confounding variable, and how can you control for it?",
         answer="A confounding variable influences both the independent and dependent variable, creating a spurious association between them.",
         deep_dive="Control via randomization, where A/B tests balance confounders across groups on average, stratification, analyzing within subgroups, or including it as a covariate in regression. You can only control for confounders you've identified — unmeasured ones remain a fundamental limit of observational data."),
    dict(category="statistics", difficulty="Intermediate", frequency=3,
         tags=["multicollinearity", "regression"],
         question="What is multicollinearity, and why is it a problem in regression?",
         answer="Multicollinearity occurs when predictors are highly correlated with each other, making it hard to isolate each variable's individual effect.",
         deep_dive="This inflates coefficient variance, making estimates unstable and hard to interpret, though it doesn't necessarily hurt overall predictive accuracy. Detect it with Variance Inflation Factor; fix it by removing or combining features, Ridge regression, or PCA."),
    dict(category="statistics", difficulty="Beginner", frequency=3,
         tags=["sampling", "sample-size"],
         question="What is the difference between a population and a sample, and why does sample size matter?",
         answer="A population is the entire group you want to draw conclusions about; a sample is the observed subset used to estimate its characteristics.",
         deep_dive="Larger samples produce lower-variance, more precise estimates and more power to detect real effects, though with diminishing returns, since standard error shrinks proportional to one over the square root of n."),
    dict(category="statistics", difficulty="Beginner", frequency=4,
         tags=["normal-distribution", "gaussian"],
         question="What is a normal distribution, and why does it show up so often in statistics and ML?",
         answer="The normal, or Gaussian, distribution is a symmetric, bell-shaped distribution defined by its mean and variance.",
         deep_dive="It shows up often partly because of the Central Limit Theorem and partly because of convenient math, like closed-form likelihoods. Real-world data is frequently not normal — heavy tails and skew — and assuming normality when it doesn't hold can mislead a model's conclusions."),
    dict(category="statistics", difficulty="Advanced", frequency=3,
         tags=["mle", "map", "bayesian-inference"],
         question="What is the difference between MLE and MAP estimation?",
         answer="MLE finds parameters that maximize the likelihood of observed data alone. MAP maximizes the posterior, combining the likelihood with a prior belief about the parameters.",
         deep_dive="MAP is effectively MLE plus a regularization-like pull toward the prior; as data grows, the prior's influence shrinks and MAP converges toward MLE. Concretely, L2 regularization corresponds to MAP with a Gaussian prior on weights, and L1 to a Laplace prior."),

    # ---------------- MLOPS ----------------
    dict(category="mlops", difficulty="Intermediate", frequency=5,
         tags=["model-drift", "monitoring"],
         question="What is model drift, and how do you detect it in production?",
         answer="Model drift is performance degradation over time as real-world data diverges from training data — data drift, where inputs change, or concept drift, where the input-target relationship changes.",
         deep_dive="Detect it by monitoring input and prediction distributions against a training baseline, using tests like KS-test or PSI, and by tracking real outcome labels once available to measure live accuracy degradation. Concept drift may only surface once delayed ground-truth labels arrive."),
    dict(category="mlops", difficulty="Intermediate", frequency=3,
         tags=["online-inference", "batch-inference"],
         question="What's the difference between online and batch inference, and how do you decide which to use?",
         answer="Batch inference runs predictions on many inputs periodically, favoring throughput; online inference serves predictions in real time, favoring low latency.",
         deep_dive="Use online when predictions need fresh, request-time data, like fraud detection on a live transaction; use batch when latency doesn't matter and results can be precomputed, like nightly recommendations. Streaming is a common middle ground."),
    dict(category="mlops", difficulty="Intermediate", frequency=3,
         tags=["feature-store", "training-serving-skew"],
         question="What is a feature store, and what problem does it solve?",
         answer="A feature store centralizes computing and serving ML features consistently across training, an offline store, and production, an online store.",
         deep_dive="It mainly solves training-serving skew — features computed differently at training versus inference time, silently degrading the model. Point-in-time correctness ensures training data only uses values that would actually have been available historically, avoiding label leakage."),
    dict(category="mlops", difficulty="Intermediate", frequency=4,
         tags=["ab-testing", "canary-deployment"],
         question="What is A/B testing, and how do you apply it to evaluate a new ML model in production?",
         answer="A/B testing randomly splits live traffic between a control and treatment model, comparing a target metric to see if the new model causes a real improvement.",
         deep_dive="Typically you canary a small percentage of traffic first, monitor target and guardrail metrics like latency and error rate, then ramp up gradually. Watch for the peeking problem — stopping early on noise before reaching statistical significance."),
    dict(category="mlops", difficulty="Intermediate", frequency=3,
         tags=["ci-cd", "model-registry"],
         question="What is CI/CD for machine learning, and how does it differ from traditional software CI/CD?",
         answer="Traditional CI/CD automates testing and deploying code. ML CI/CD also versions and validates data and model artifacts, and retrains and re-evaluates when data changes, not just code.",
         deep_dive="Common tooling includes MLflow, DVC, Kubeflow, and a model registry tracking versions, stage, and metadata — testing also has to cover schema changes and performance regressions, not just unit tests."),
    dict(category="mlops", difficulty="Intermediate", frequency=4,
         tags=["model-monitoring", "observability"],
         question="What is model monitoring, and what should you actually track once a model is live?",
         answer="Model monitoring is ongoing observation of a deployed model's inputs, outputs, and performance to catch problems early.",
         deep_dive="Beyond infrastructure metrics like latency and error rate, track input and prediction distributions for drift, and, once available, real outcome labels to measure live precision and recall, plus fairness metrics across important subgroups. Delayed feedback loops are a core challenge here."),
    dict(category="mlops", difficulty="Intermediate", frequency=3,
         tags=["model-versioning", "reproducibility"],
         question="What is the difference between model versioning and data versioning, and why do you need both?",
         answer="Model versioning tracks trained artifacts, like weights, architecture, and hyperparameters; data versioning tracks the dataset snapshots used to train each version.",
         deep_dive="The same code with different data produces a genuinely different model — without data versioning you can't reproduce a past result or debug behavior differences. Tools like DVC or lakeFS handle this; reproducibility needs code, data, hyperparameters, and environment all pinned together."),
    dict(category="mlops", difficulty="Intermediate", frequency=3,
         tags=["shadow-deployment", "canary-deployment"],
         question="What's the difference between a shadow deployment and a canary deployment?",
         answer="A shadow deployment runs the new model in parallel on live traffic, logging predictions for comparison, but never returns them to users. A canary serves the new model's predictions to a small percentage of real traffic.",
         deep_dive="These are often used in sequence — shadow first to validate correctness and latency with zero user risk, canary next to validate real-world impact with limited exposure, before a full rollout."),

    # ---------------- GENERATIVE AI & LLMs ----------------
    dict(category="generative-ai", difficulty="Intermediate", frequency=4,
         tags=["llm", "scaling-laws"],
         question="What makes a Large Language Model 'large,' and why does scale matter?",
         answer="LLMs are 'large' in parameter count, often tens to hundreds of billions, and in pretraining data size, often hundreds of billions to trillions of tokens.",
         deep_dive="Scaling laws show that as you increase model size, data, and compute together, performance improves smoothly and predictably, and some abilities like multi-step reasoning and in-context learning emerge more reliably past certain scale thresholds. The Chinchilla finding showed many earlier large models were undertrained relative to their size — optimal scaling balances model and data size together."),
    dict(category="generative-ai", difficulty="Intermediate", frequency=5,
         tags=["pretraining", "rlhf", "alignment"],
         question="What is the difference between pretraining, fine-tuning, and RLHF for a model like ChatGPT?",
         answer="Pretraining trains next-token prediction over a massive, broad corpus. Supervised fine-tuning trains further on curated instruction-following examples. RLHF fine-tunes toward outputs humans actually prefer, using a reward model trained on human preference comparisons.",
         deep_dive="Classic RLHF uses an algorithm called PPO to optimize against the learned reward model; newer alternatives like DPO skip training a separate reward model entirely, optimizing preferences more directly."),
    dict(category="generative-ai", difficulty="Beginner", frequency=5,
         tags=["prompting", "few-shot", "chain-of-thought"],
         question="What's the difference between zero-shot, few-shot, and chain-of-thought prompting?",
         answer="Zero-shot asks the model to perform a task directly with no examples; few-shot includes example input-output pairs in the prompt; chain-of-thought asks the model to reason step by step before answering.",
         deep_dive="This is all 'in-context learning' — the model isn't updating its weights, it's using the prompt itself as a temporary task specification at inference time. Chain-of-thought often substantially improves performance on multi-step reasoning tasks."),
    dict(category="generative-ai", difficulty="Beginner", frequency=5,
         tags=["hallucination", "llm-limitations"],
         question="What is a hallucination in the context of LLMs, and why does it happen?",
         answer="A hallucination is fluent, confident text that's factually incorrect or fabricated, like an invented citation or statistic.",
         deep_dive="LLMs are trained to predict statistically plausible next tokens, not to verify truth — there's no built-in mechanism distinguishing 'this sounds right' from 'this is true,' especially for rare or ambiguous facts. Mitigations include retrieval-augmented generation, better calibration during fine-tuning, and prompting the model to cite sources or express uncertainty."),
    dict(category="generative-ai", difficulty="Intermediate", frequency=5,
         tags=["rag", "retrieval"],
         question="What is Retrieval-Augmented Generation, and why is it useful?",
         answer="RAG combines a retrieval system, typically vector search over a document collection, with a generative LLM — relevant documents are retrieved per query and inserted into the prompt as context.",
         deep_dive="This lets a model answer questions about information outside its training data, like private documents or recent events, and reduces hallucination by grounding answers in real source material the model can cite or draw from directly."),
    dict(category="generative-ai", difficulty="Intermediate", frequency=4,
         tags=["context-window", "transformer-limits"],
         question="What is a context window, and why can't LLMs just have an infinite one?",
         answer="The context window is the maximum number of tokens, input plus output, a model can attend to at once.",
         deep_dive="Standard self-attention's compute and memory cost scales quadratically with sequence length, so naively extending context gets expensive fast. Techniques like sparse attention, sliding windows, and optimized attention kernels such as FlashAttention push context windows longer without a full quadratic blow-up."),
    dict(category="generative-ai", difficulty="Intermediate", frequency=4,
         tags=["embeddings", "vector-search"],
         question="What is an embedding model, and how does vector similarity search work?",
         answer="An embedding model maps text or images into a dense vector such that semantically similar inputs land close together in that space.",
         deep_dive="Vector search finds the nearest stored embeddings to a query embedding, typically using cosine similarity or dot product, accelerated by approximate nearest-neighbor indexes like HNSW or IVF so search stays fast at large scale — this is the retrieval half of RAG."),
    dict(category="generative-ai", difficulty="Beginner", frequency=4,
         tags=["temperature", "sampling", "decoding"],
         question="What does 'temperature' control when generating text from an LLM?",
         answer="Temperature scales the logits before the softmax that turns them into a probability distribution over the next token — lower temperature sharpens the distribution toward the most likely tokens, higher flattens it.",
         deep_dive="Temperature near zero makes output nearly deterministic and repetitive-safe; higher temperature increases diversity and creativity but raises the risk of incoherent or off-topic output. Top-k and top-p, or nucleus, sampling are often combined with temperature to control the candidate pool."),
    dict(category="generative-ai", difficulty="Intermediate", frequency=4,
         tags=["fine-tuning", "lora", "peft"],
         question="What is LoRA, and why is it useful for fine-tuning large models?",
         answer="LoRA, or Low-Rank Adaptation, freezes the pretrained model's weights and injects small, trainable low-rank matrices into specific layers, training only those instead of the full model.",
         deep_dive="This drastically cuts the number of trainable parameters and memory needed to fine-tune a large model, making task-specific adaptation feasible on much smaller hardware, while the original weights stay untouched and swappable between different LoRA adapters."),
    dict(category="generative-ai", difficulty="Advanced", frequency=3,
         tags=["moe", "mixture-of-experts"],
         question="What is a Mixture of Experts architecture, and why do some LLMs use it?",
         answer="A Mixture of Experts model replaces a single dense feed-forward layer with multiple 'expert' sub-networks, and a learned router activates only a small subset of experts for each token.",
         deep_dive="This lets the total parameter count scale up massively while keeping the compute cost per token roughly constant, since most parameters are inactive for any given token — a way to get more model capacity without a proportional rise in inference cost."),
    dict(category="generative-ai", difficulty="Intermediate", frequency=4,
         tags=["agents", "tool-use", "function-calling"],
         question="What does it mean for an LLM to use 'tools' or act as an 'agent'?",
         answer="Tool use means the model can call external functions, like search, calculators, or code execution, mid-conversation and incorporate the results into its response, rather than relying only on its own internal knowledge.",
         deep_dive="An 'agent' typically wraps this in a loop: the model plans a step, calls a tool, observes the result, and decides the next step, continuing until the task is done — useful for tasks needing fresh information, precise computation, or real-world side effects that a language model alone can't reliably produce."),
    dict(category="generative-ai", difficulty="Intermediate", frequency=3,
         tags=["evaluation", "benchmarks"],
         question="Why is evaluating LLMs harder than evaluating a traditional classifier?",
         answer="Traditional classifiers have one correct label to check against; LLM outputs are open-ended text where many different phrasings can be equally correct, making simple exact-match scoring unreliable.",
         deep_dive="Evaluation approaches include benchmark suites with multiple-choice or exact-match tasks, human preference comparisons, and using another LLM as a judge — each with tradeoffs between scalability, cost, and how well they correlate with real-world usefulness."),

    # ---------------- SQL ----------------
    dict(category="sql", difficulty="Beginner", frequency=5,
         tags=["joins", "sql-basics"],
         question="What's the difference between INNER JOIN, LEFT JOIN, and FULL OUTER JOIN?",
         answer="INNER JOIN returns only rows with matches in both tables. LEFT JOIN returns all rows from the left table plus matched rows from the right, with NULLs where there's no match. FULL OUTER JOIN returns all rows from both tables, with NULLs wherever a match is missing on either side.",
         deep_dive="Choosing the right join type matters for correctness — a common bug is using INNER JOIN when you actually need LEFT JOIN to preserve rows without a match, silently dropping data from your results."),
    dict(category="sql", difficulty="Beginner", frequency=4,
         tags=["where", "having", "aggregation"],
         question="What's the difference between WHERE and HAVING?",
         answer="WHERE filters individual rows before any grouping or aggregation happens; HAVING filters groups after a GROUP BY aggregation has been computed.",
         deep_dive="You can't reference an aggregate function like COUNT() or SUM() in a WHERE clause for that reason — it has to go in HAVING, since the aggregate doesn't exist yet at the row-filtering stage."),
    dict(category="sql", difficulty="Beginner", frequency=4,
         tags=["primary-key", "foreign-key"],
         question="What is a primary key versus a foreign key?",
         answer="A primary key uniquely identifies each row in a table and can't be NULL or duplicated. A foreign key is a column in one table that references a primary key in another table, enforcing a relationship between them.",
         deep_dive="Foreign keys are how relational databases enforce referential integrity — the database will reject an insert or update that would create a foreign key value with no matching primary key, preventing orphaned records."),
    dict(category="sql", difficulty="Intermediate", frequency=4,
         tags=["normalization", "database-design"],
         question="What is database normalization, and why would you denormalize?",
         answer="Normalization organizes data to reduce redundancy and avoid update anomalies, typically by splitting data into related tables. Denormalization deliberately reintroduces some redundancy, usually to improve read performance by avoiding expensive joins.",
         deep_dive="Analytical and reporting workloads often denormalize, using wide tables or star schemas, since reads dominate and joins are costly at scale, while transactional systems usually stay more normalized to keep writes consistent and avoid anomalies."),
    dict(category="sql", difficulty="Intermediate", frequency=4,
         tags=["indexes", "query-performance"],
         question="What is an index, and what's the tradeoff of adding one?",
         answer="An index is a separate data structure, often a B-tree, that lets the database find rows matching a condition much faster than scanning the whole table. The tradeoff is that indexes take extra storage and slow down writes, since the index has to be updated too.",
         deep_dive="Indexing the right columns — typically ones used heavily in WHERE clauses, JOIN conditions, or ORDER BY — is a balancing act; over-indexing a write-heavy table can hurt more than it helps."),
    dict(category="sql", difficulty="Intermediate", frequency=3,
         tags=["subquery", "cte"],
         question="What's the difference between a subquery and a CTE (Common Table Expression)?",
         answer="A subquery is a query nested inside another query, often in a WHERE or FROM clause. A CTE, defined with WITH, names a temporary result set you can reference like a table within the main query, often improving readability for complex, multi-step logic.",
         deep_dive="CTEs can also be recursive, using WITH RECURSIVE, which is useful for hierarchical data like organizational charts or category trees that a plain subquery can't easily express."),
    dict(category="sql", difficulty="Intermediate", frequency=3,
         tags=["acid", "transactions"],
         question="What does ACID stand for, and why does it matter?",
         answer="ACID stands for Atomicity, Consistency, Isolation, and Durability — properties that guarantee database transactions are processed reliably, even in the face of errors, crashes, or concurrent access.",
         deep_dive="Atomicity means a transaction fully succeeds or fully rolls back; Isolation determines how concurrent transactions interact, controlled by isolation levels like READ COMMITTED or SERIALIZABLE; Durability guarantees committed data survives a crash."),
    dict(category="sql", difficulty="Advanced", frequency=4,
         tags=["window-functions", "sql-advanced"],
         question="What are window functions, and how do they differ from GROUP BY aggregation?",
         answer="A window function performs a calculation across a set of rows related to the current row, a 'window', without collapsing those rows into a single output row, unlike GROUP BY, which aggregates rows into fewer summary rows.",
         deep_dive="Functions like ROW_NUMBER(), RANK(), and running totals with SUM() OVER (PARTITION BY ... ORDER BY ...) are classic window function use cases — useful for ranking each employee's salary within their department while still showing every employee row."),
    dict(category="sql", difficulty="Beginner", frequency=4,
         tags=["null-handling", "sql-basics"],
         question="How does SQL handle NULL, and why can it be tricky in comparisons?",
         answer="NULL represents an unknown or missing value, and any direct comparison with NULL using = or != returns NULL, neither true nor false, which is why you need IS NULL or IS NOT NULL instead.",
         deep_dive="This also affects aggregate functions, which mostly ignore NULLs by default, and joins, since a NULL foreign key won't match anything in an INNER JOIN — both can silently drop rows from results if you're not careful."),
    dict(category="sql", difficulty="Intermediate", frequency=4,
         tags=["query-optimization", "execution-plan"],
         question="How would you approach optimizing a slow SQL query?",
         answer="Start by examining the query execution plan, using EXPLAIN or EXPLAIN ANALYZE, to see how the database is actually executing it — looking for full table scans where an index could help, expensive joins, or poor join order.",
         deep_dive="Common fixes include adding a targeted index, rewriting a correlated subquery as a join, selecting only needed columns instead of SELECT *, and checking that the statistics used by the query planner are up to date."),

    # ---------------- NUMPY ----------------
    dict(category="numpy", difficulty="Intermediate", frequency=5,
         tags=["broadcasting", "vectorization"],
         question="What is broadcasting in NumPy?",
         answer="Broadcasting lets NumPy perform element-wise operations on arrays of different shapes by implicitly expanding the smaller array along mismatched dimensions, without actually copying data, as long as the shapes are compatible.",
         deep_dive="Two dimensions are compatible if they're equal or one of them is 1 — which is why you can add a shape-(3,) vector to every row of a shape-(5,3) matrix without writing an explicit loop."),
    dict(category="numpy", difficulty="Beginner", frequency=4,
         tags=["vectorization", "performance", "ndarray"],
         question="Why is NumPy faster than plain Python lists for numerical operations?",
         answer="NumPy arrays store data in contiguous memory blocks of a single fixed dtype, and operations are implemented in compiled C code that processes the whole array at once, avoiding the overhead of Python's per-element loop and dynamic typing.",
         deep_dive="Python lists store pointers to separately allocated objects, adding memory overhead and indirection. NumPy's contiguous layout also enables CPU cache efficiency and SIMD instructions that plain Python loops can't take advantage of."),
    dict(category="numpy", difficulty="Intermediate", frequency=4,
         tags=["views", "copies", "memory"],
         question="What's the difference between a NumPy view and a copy?",
         answer="A view shares the same underlying memory as the original array, so modifying the view modifies the original. A copy is a completely independent array in its own memory; modifying it leaves the original untouched.",
         deep_dive="Basic slicing usually returns a view, while operations like fancy indexing with a list of indices or boolean masking return a copy — knowing which you're getting matters a lot for avoiding accidental mutation bugs."),
    dict(category="numpy", difficulty="Beginner", frequency=4,
         tags=["axis", "aggregation", "ndarray"],
         question="What does the `axis` parameter control in functions like np.sum() or np.mean()?",
         answer="The axis parameter controls which dimension the operation collapses over — axis=0 typically aggregates down columns, across rows, and axis=1 aggregates across rows, along columns, for a 2D array.",
         deep_dive="A reliable mental model: axis=0 removes the row dimension, axis=1 removes the column dimension, by collapsing along that axis — this trips up almost everyone the first few times."),
    dict(category="numpy", difficulty="Intermediate", frequency=3,
         tags=["matrix-multiplication", "dot-product"],
         question="What is the difference between np.dot() and element-wise multiplication with *?",
         answer="The * operator multiplies arrays element-by-element, requiring matching or broadcastable shapes. np.dot(), or the @ operator, performs proper matrix multiplication, summing products across the shared dimension.",
         deep_dive="For 1D arrays, np.dot() computes the inner product, a scalar; for 2D arrays, it follows standard matrix multiplication rules, where the inner dimensions must match."),
    dict(category="numpy", difficulty="Beginner", frequency=3,
         tags=["dtype", "memory-optimization"],
         question="What is a NumPy dtype, and why does it matter for memory and performance?",
         answer="A dtype specifies the data type of every element in an array, like int32, float64, or bool, and unlike Python lists, all elements in a NumPy array share the same dtype.",
         deep_dive="Choosing a smaller dtype, like float32 instead of float64, when full precision isn't needed can roughly halve memory usage and speed up computation, which matters a lot when working with large arrays or training models on limited memory."),
    dict(category="numpy", difficulty="Beginner", frequency=4,
         tags=["boolean-indexing", "filtering"],
         question="How does boolean masking work in NumPy?",
         answer="A boolean mask is an array of True/False values, often produced by a condition like arr > 5, that you can use to index into the original array and select only the elements where the mask is True.",
         deep_dive="This enables concise, vectorized filtering and conditional assignment, like setting arr[arr < 0] = 0 to clip negative values to zero in a single line, without an explicit loop."),
    dict(category="numpy", difficulty="Beginner", frequency=3,
         tags=["reshape", "array-manipulation"],
         question="What does np.reshape() do, and what does -1 mean as a dimension?",
         answer="reshape() changes an array's shape without changing its data or total number of elements, as long as the new shape is compatible with the original element count.",
         deep_dive="Passing -1 for one dimension tells NumPy to infer that dimension automatically based on the array's size and the other specified dimensions — handy when you know one dimension but not the other, like flattening to shape (n, -1)."),

    # ---------------- PANDAS ----------------
    dict(category="pandas", difficulty="Beginner", frequency=4,
         tags=["series", "dataframe", "pandas-basics"],
         question="What's the difference between a pandas Series and a DataFrame?",
         answer="A Series is a one-dimensional labeled array — essentially a single column with an index. A DataFrame is a two-dimensional labeled table made up of multiple Series sharing the same index, like a spreadsheet or SQL table.",
         deep_dive="Selecting a single column from a DataFrame returns a Series, and many DataFrame operations are really Series operations applied across columns under the hood."),
    dict(category="pandas", difficulty="Beginner", frequency=5,
         tags=["loc", "iloc", "indexing"],
         question="What's the difference between loc and iloc?",
         answer="loc selects rows or columns by label, the actual index or column name; iloc selects by integer position, regardless of what the labels are.",
         deep_dive="This distinction matters most when an index has been customized, like a date index, or after filtering, where positions and labels diverge — using the wrong one is a very common source of off-by-one or 'wrong row' bugs."),
    dict(category="pandas", difficulty="Intermediate", frequency=4,
         tags=["merge", "join", "concat"],
         question="What's the difference between merge, join, and concat in pandas?",
         answer="merge() combines DataFrames based on common column values, like a SQL join. join() is a convenience method for combining DataFrames based on their index. concat() stacks DataFrames together along an axis without matching on keys.",
         deep_dive="merge() is the most flexible and SQL-like, supporting inner, left, right, and outer joins on specified columns; concat() is best for simply appending datasets with the same structure, like combining monthly files."),
    dict(category="pandas", difficulty="Beginner", frequency=5,
         tags=["missing-data", "fillna", "dropna"],
         question="How do you handle missing data in pandas?",
         answer="Common approaches: drop rows or columns with missing values using dropna(), fill them with a value or statistic like the mean using fillna(), or interpolate between known values with interpolate().",
         deep_dive="The right choice depends on why data is missing and how much of it there is — dropping is simplest but can lose information or bias the dataset if missingness isn't random, while imputation should be informed by the data's actual structure."),
    dict(category="pandas", difficulty="Intermediate", frequency=5,
         tags=["groupby", "split-apply-combine"],
         question="What does groupby() do, and what's the typical pattern for using it?",
         answer="groupby() splits a DataFrame into groups based on the values in one or more columns, so you can apply an aggregation, transformation, or filter to each group independently, then combine the results back together.",
         deep_dive="This follows the 'split-apply-combine' pattern — for example, grouping by category and taking the mean of price splits by category, applies mean() to each group's price column, and combines the results into a Series indexed by category."),
    dict(category="pandas", difficulty="Intermediate", frequency=3,
         tags=["vectorization", "apply", "performance"],
         question="Why should you generally prefer vectorized operations over .apply() with a custom function in pandas?",
         answer="Vectorized operations, built-in pandas or NumPy operations across whole columns, run in compiled C code, while .apply() calls a Python function once per row or column, incurring Python-level overhead for every iteration.",
         deep_dive="For simple operations, this can make vectorized code an order of magnitude faster on large datasets; .apply() is still useful for genuinely custom logic with no vectorized equivalent, but it shouldn't be the first reach for something a built-in method already handles."),
    dict(category="pandas", difficulty="Intermediate", frequency=3,
         tags=["pivot-table", "data-reshaping"],
         question="What is a pivot table in pandas, and when would you use one?",
         answer="pivot_table() reshapes data by turning unique values from one column into new columns, aggregating values from another column into the cells, similar to a pivot table in a spreadsheet.",
         deep_dive="It's useful for summarizing data along two dimensions at once, like average sales by region and month, and it handles duplicate entries via an aggregation function, default mean, unlike pivot(), which requires unique index and column combinations."),
    dict(category="pandas", difficulty="Beginner", frequency=3,
         tags=["axis", "pandas-basics"],
         question="What's the difference between axis=0 and axis=1 in pandas operations like drop() or sum()?",
         answer="axis=0 refers to operating down the rows, the default for most aggregations, summarizing each column, while axis=1 refers to operating across the columns, summarizing each row.",
         deep_dive="For drop(), axis=0 drops rows by index label and axis=1 drops columns by column name — the same underlying convention as NumPy, which is worth keeping consistent in your mental model across both libraries."),

    # ---------------- SYSTEM DESIGN ----------------
    dict(category="system-design", difficulty="Beginner", frequency=4,
         tags=["scaling", "system-design-basics"],
         question="What's the difference between horizontal and vertical scaling?",
         answer="Vertical scaling adds more resources, like CPU or RAM, to a single machine; horizontal scaling adds more machines and distributes load across them.",
         deep_dive="Horizontal scaling generally offers better fault tolerance and near-unlimited scalability but adds complexity, like load balancing and data consistency across nodes, while vertical scaling is simpler but hits a hard ceiling and creates a single point of failure."),
    dict(category="system-design", difficulty="Beginner", frequency=4,
         tags=["load-balancing", "availability"],
         question="What is a load balancer, and what problem does it solve?",
         answer="A load balancer distributes incoming traffic across multiple backend servers, preventing any single server from being overwhelmed and enabling horizontal scaling and high availability.",
         deep_dive="Common strategies include round robin, least connections, and weighted distribution based on server capacity; load balancers also enable zero-downtime deployments by routing traffic away from servers being updated."),
    dict(category="system-design", difficulty="Intermediate", frequency=4,
         tags=["sql-vs-nosql", "database-design"],
         question="What's the difference between SQL and NoSQL databases, and how do you choose?",
         answer="SQL databases are relational, with structured schemas and strong consistency guarantees, well-suited to complex queries and transactional data. NoSQL databases offer flexible schemas and typically prioritize horizontal scalability over strict consistency.",
         deep_dive="Choose based on your data's structure and access patterns — relational data with complex relationships and a need for strong consistency favors SQL; high-volume, loosely-structured, or rapidly evolving data favors NoSQL, though the line has blurred as many databases now support both styles."),
    dict(category="system-design", difficulty="Beginner", frequency=4,
         tags=["caching", "performance"],
         question="What is caching, and where would you add a cache in a typical web application?",
         answer="Caching stores frequently accessed data in a fast-access layer, usually memory, to avoid recomputing or re-fetching it from a slower source like a database, reducing latency and load.",
         deep_dive="Common layers include a CDN for static assets, an in-memory cache like Redis for database query results, and client-side caching in the browser — each trades off freshness for speed, which is why cache invalidation strategy matters as much as the caching itself."),
    dict(category="system-design", difficulty="Advanced", frequency=3,
         tags=["cap-theorem", "distributed-systems"],
         question="What is the CAP theorem?",
         answer="The CAP theorem states that a distributed system can only guarantee two of three properties at once during a network partition: Consistency, Availability, and Partition tolerance.",
         deep_dive="Since network partitions are unavoidable in real distributed systems, the practical choice is really between consistency and availability when a partition occurs — this is why a strongly consistent SQL database and an eventually consistent NoSQL store make different tradeoffs."),
    dict(category="system-design", difficulty="Advanced", frequency=4,
         tags=["ml-system-design", "model-serving"],
         question="How would you design a system to serve ML model predictions at scale?",
         answer="At a high level: a load balancer distributes requests across multiple model-serving instances, each loading the model into memory for fast inference; a feature store or cache supplies precomputed features; and the system is monitored for latency, throughput, and prediction drift.",
         deep_dive="Key decisions include batch versus real-time inference, whether to use GPU instances for heavier models, how to version and roll out new models safely via canary deployments, and how to keep serving latency low — techniques like model quantization, distillation, or caching repeated predictions all help here."),
    dict(category="system-design", difficulty="Intermediate", frequency=3,
         tags=["message-queues", "asynchronous-processing"],
         question="What is a message queue, and why would you use one between services?",
         answer="A message queue lets one service publish messages that another service consumes asynchronously, decoupling the producer and consumer so they don't need to be online or fast at the same time.",
         deep_dive="This smooths out traffic spikes, since the queue buffers requests instead of overwhelming a downstream service, enables retry logic for failed processing, and lets services scale and fail independently — common examples include Kafka, RabbitMQ, and cloud-managed queues like SQS."),
    dict(category="system-design", difficulty="Advanced", frequency=4,
         tags=["recommendation-systems", "ml-system-design"],
         question="How would you design a basic recommendation system?",
         answer="A common approach combines candidate generation, quickly narrowing millions of items down to a few hundred relevant candidates, often via collaborative filtering or embeddings, with ranking, a more expensive model that scores and orders those candidates precisely.",
         deep_dive="Candidate generation needs to be fast and broad, recall-focused, while ranking can afford to be slower and more precise since it's working with a much smaller set — this two-stage funnel is the standard pattern behind most large-scale recommendation systems."),
    dict(category="system-design", difficulty="Intermediate", frequency=3,
         tags=["consistency", "distributed-systems"],
         question="What's the difference between strong consistency and eventual consistency?",
         answer="Strong consistency guarantees that once a write completes, every subsequent read sees that write immediately, everywhere. Eventual consistency guarantees that if no new writes occur, all reads will eventually converge on the latest value, but there may be a window where different nodes return stale data.",
         deep_dive="Eventual consistency trades a brief window of staleness for better availability and performance in distributed systems — acceptable for something like a social media like-count, but usually not for a bank account balance, where strong consistency matters more."),
    dict(category="system-design", difficulty="Intermediate", frequency=3,
         tags=["rate-limiting", "api-design"],
         question="What's the difference between rate limiting and throttling, and why does an API need either?",
         answer="Rate limiting restricts how many requests a client can make in a given time window, often rejecting or queuing requests over the limit; throttling typically refers to slowing down, rather than outright rejecting, excess requests.",
         deep_dive="Both protect a service from being overwhelmed, whether by misbehaving clients, traffic spikes, or abuse. Common implementations include token bucket and sliding window algorithms; limits are often tiered by user or API key to support fair usage across customers."),
]
